# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 12:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('abstract', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('isBlog', models.BooleanField(default=True)),
                ('cover', models.CharField(blank=True, default='', max_length=300)),
                ('cover_big', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mantra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('mantra', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('facebook_username', models.CharField(max_length=50)),
                ('twitter_username', models.CharField(max_length=50)),
                ('medium_username', models.CharField(max_length=50)),
                ('github_username', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('img2x', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=500)),
                ('mantra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Mantra')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='techs',
            field=models.ManyToManyField(to='app.Tech'),
        ),
        migrations.AddField(
            model_name='entry',
            name='techs',
            field=models.ManyToManyField(to='app.Tech'),
        ),
    ]
