# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160210_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name_fixed',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
