# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160203_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='techs',
            field=models.ManyToManyField(to='app.Tech'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
