# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160203_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='tech',
            name='img',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
