# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160203_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
