# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160203_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mantra',
            field=models.ManyToManyField(to='app.Mantra'),
        ),
    ]
