# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_person_mantra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mantra',
        ),
        migrations.AddField(
            model_name='person',
            name='mantra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Mantra'),
            preserve_default=False,
        ),
    ]
