# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160206_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mantra',
        ),
    ]
