# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160207_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cover',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
        migrations.AddField(
            model_name='entry',
            name='cover_big',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=tinymce.models.HTMLField(max_length=10000),
        ),
    ]
